version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=emailsendertimes
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3307:3306"

  springbootapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: appspring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3307/emailsendertimes
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
